# Generated by Django 4.2 on 2023-04-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_braiile_picture_braiilepicture"),
    ]

    operations = [
        migrations.AddField(
            model_name="braiilepicture",
            name="braille",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="braiilepicture",
            name="image",
            field=models.ImageField(
                default="media/default_img.jpeg", null=True, upload_to=""
            ),
        ),
    ]
