# Generated by Django 4.2 on 2023-05-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_koreanpicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="braiilepicture",
            name="image",
            field=models.ImageField(
                default="media/Braille/default_img.jpeg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="koreanpicture",
            name="image",
            field=models.ImageField(
                default="media/Korean/default_img.jpeg", null=True, upload_to=""
            ),
        ),
    ]
