# Generated by Django 4.2 on 2023-05-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_braiilepicture_image_alter_koreanpicture_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="braiilepicture",
            name="image",
            field=models.ImageField(null=True, upload_to="media/Braille/"),
        ),
        migrations.AlterField(
            model_name="koreanpicture",
            name="image",
            field=models.ImageField(null=True, upload_to="media/Korean/"),
        ),
    ]
